# 2. Node AntiAffinity: 특정 노드(Label이 있는 노드)를 피해서 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-anti-affinity-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: NotIn
                    values:
                      - ssd
      containers:
        - name: my-container
          image: nginx